language: c

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y default-jdk-headless ; fi

script:
  - make
